"""
Apply a heightmap as vertex displacement to a 3D mesh and export as GLB/OBJ.

Pipeline:
  1. Sample heightmap value at each vertex's UV coordinate
  2. Displace vertex along its normal by height * scale_factor
  3. Recompute face normals
  4. Export via trimesh (GLB for Gradio, OBJ for Blender)

VecSet bridge: if a mesh was generated by 3DShape2VecSet (exported as OBJ/PLY),
it can be loaded via MeshProcessor and passed directly here.

Usage:
  python texture3d/texture_mapper.py --mesh sphere.obj --heightmap outputs/hm.png --output out.glb
"""
import argparse
from pathlib import Path
from typing import Optional, Union

import numpy as np
import trimesh
from PIL import Image

from texture3d.mesh_processor import MeshProcessor


class HeightmapTextureMapper:
    """Displace mesh vertices along normals using a heightmap image."""

    def __init__(
        self,
        scale_factor: float = 0.05,
        smooth_iterations: int = 0,
    ):
        self.scale_factor = scale_factor
        self.smooth_iterations = smooth_iterations

    def _sample_heightmap(self, heightmap: np.ndarray, uvs: np.ndarray) -> np.ndarray:
        """Bilinear sampling of heightmap at UV coordinates.

        uvs: (N, 2) in [0, 1] range
        returns: (N,) float32 in [0, 1]
        """
        H, W = heightmap.shape[:2]
        u = np.clip(uvs[:, 0], 0, 1)
        v = np.clip(1 - uvs[:, 1], 0, 1)  # flip V (image Y-axis is top-down)

        x = u * (W - 1)
        y = v * (H - 1)

        x0, y0 = np.floor(x).astype(int), np.floor(y).astype(int)
        x1, y1 = np.minimum(x0 + 1, W - 1), np.minimum(y0 + 1, H - 1)

        wx = (x - x0)[..., None]
        wy = (y - y0)[..., None]

        def at(r, c):
            return heightmap[r, c].astype(np.float32)

        val = (
            at(y0, x0) * (1 - wx) * (1 - wy)
            + at(y0, x1) * wx * (1 - wy)
            + at(y1, x0) * (1 - wx) * wy
            + at(y1, x1) * wx * wy
        )
        return val.squeeze(-1) / 255.0

    def apply(
        self,
        mesh_processor: MeshProcessor,
        heightmap: Union[str, Image.Image, np.ndarray],
        scale_factor: Optional[float] = None,
        uv_method: str = "auto",
    ) -> trimesh.Trimesh:
        scale = scale_factor if scale_factor is not None else self.scale_factor

        if not mesh_processor.has_uv:
            mesh_processor.generate_uv(method=uv_method)

        if isinstance(heightmap, str):
            heightmap = Image.open(heightmap).convert("L")
        if isinstance(heightmap, Image.Image):
            heightmap = np.array(heightmap)
        heightmap = heightmap.astype(np.float32)

        uvs = mesh_processor.get_uv()
        heights = self._sample_heightmap(heightmap, uvs)

        new_verts = mesh_processor.vertices.copy()
        normals = mesh_processor.vertex_normals
        new_verts += normals * (heights[:, None] * scale)

        displaced = trimesh.Trimesh(
            vertices=new_verts,
            faces=mesh_processor.faces,
            process=False,
        )
        displaced.visual = mesh_processor.mesh.visual

        # Optional Laplacian smoothing on displaced vertices
        for _ in range(self.smooth_iterations):
            displaced = trimesh.smoothing.filter_laplacian(displaced, iterations=1)

        displaced.fix_normals()
        return displaced


def apply_heightmap_to_mesh(
    mesh_path: str,
    heightmap_path: str,
    output_path: str,
    scale_factor: float = 0.05,
    uv_method: str = "auto",
    smooth_iterations: int = 0,
    mesh_type: str = "auto",
):
    """High-level convenience function."""
    if mesh_type == "auto":
        if mesh_path == "sphere":
            mp = MeshProcessor.sphere(subdivisions=4)
        elif mesh_path == "plane":
            mp = MeshProcessor.plane()
        elif mesh_path == "box":
            mp = MeshProcessor.box()
        else:
            mp = MeshProcessor(mesh_path)
    else:
        mp = MeshProcessor(mesh_path)

    mapper = HeightmapTextureMapper(scale_factor=scale_factor, smooth_iterations=smooth_iterations)
    displaced = mapper.apply(mp, heightmap_path, uv_method=uv_method)

    output_path = output_path or Path(mesh_path).stem + "_textured.glb"
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    displaced.export(output_path)
    print(f"Textured mesh exported: {output_path}")
    return displaced


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Apply heightmap to 3D mesh")
    parser.add_argument("--mesh", default="sphere",
                        help="OBJ/PLY/STL path or primitive: sphere, plane, box")
    parser.add_argument("--heightmap", required=True)
    parser.add_argument("--output", default="outputs/textured.glb")
    parser.add_argument("--scale", type=float, default=0.05, help="Displacement scale factor")
    parser.add_argument("--uv", choices=["auto", "xatlas", "sphere", "angle"], default="auto")
    parser.add_argument("--smooth", type=int, default=0, help="Laplacian smoothing iterations")
    args = parser.parse_args()

    apply_heightmap_to_mesh(
        args.mesh, args.heightmap, args.output,
        scale_factor=args.scale, uv_method=args.uv, smooth_iterations=args.smooth,
    )
