"""
Diffusion-based heightmap generation with LoRA fine-tuning.

Architecture:
  Base model : Stable Diffusion 1.5 img2img pipeline (diffusers)
  Conditioning: CLIP image encoder (IP-Adapter-style feature injection)
  Adapter     : LoRA rank=4, alpha=16 on UNet cross-attention layers (PEFT)
  Output      : Grayscale heightmap PNG

Fine-tuning uses the synthetic (texture → heightmap) pairs generated by
data/heightmap_generator.py.  Training requires ~6 GB VRAM (A100 / 4090).
For CPU inference, use strength=0.9 and num_inference_steps=20.
"""
import os
from pathlib import Path
from typing import Optional, Union

import numpy as np
import torch
from PIL import Image


class HeightmapDiffusionPipeline:
    """Wrapper around a LoRA-patched SD img2img pipeline for heightmap generation."""

    BASE_MODEL = "runwayml/stable-diffusion-v1-5"
    PROMPT = (
        "grayscale surface heightmap, smooth displacement field, "
        "tactile texture relief map, no color, high detail"
    )
    NEGATIVE_PROMPT = "color, blurry, artifacts, text, watermark"

    def __init__(
        self,
        lora_weights_path: Optional[str] = None,
        device: Optional[str] = None,
        use_float16: bool = True,
    ):
        self.device = torch.device(device or ("cuda" if torch.cuda.is_available() else "cpu"))
        self.dtype = torch.float16 if (use_float16 and self.device.type == "cuda") else torch.float32
        self.pipeline = None
        self.lora_weights_path = lora_weights_path
        self._loaded = False

    def _load(self):
        if self._loaded:
            return
        try:
            from diffusers import StableDiffusionImg2ImgPipeline
        except ImportError as e:
            raise ImportError("Install diffusers: pip install diffusers>=0.27.0") from e

        print(f"Loading base model: {self.BASE_MODEL}")
        pipe = StableDiffusionImg2ImgPipeline.from_pretrained(
            self.BASE_MODEL,
            torch_dtype=self.dtype,
            safety_checker=None,
            requires_safety_checker=False,
        )
        pipe = pipe.to(self.device)
        pipe.enable_attention_slicing()

        if self.lora_weights_path and Path(self.lora_weights_path).exists():
            print(f"Loading LoRA weights from {self.lora_weights_path}")
            pipe.unet.load_attn_procs(self.lora_weights_path)

        self.pipeline = pipe
        self._loaded = True

    @torch.no_grad()
    def generate(
        self,
        texture_image: Union[str, Image.Image],
        strength: float = 0.8,
        guidance_scale: float = 7.5,
        num_inference_steps: int = 30,
        seed: Optional[int] = 42,
        output_size: int = 512,
    ) -> Image.Image:
        """Generate a grayscale heightmap from a texture image."""
        self._load()

        if isinstance(texture_image, str):
            texture_image = Image.open(texture_image).convert("RGB")

        texture_image = texture_image.resize((output_size, output_size), Image.LANCZOS)

        generator = torch.Generator(device=self.device)
        if seed is not None:
            generator.manual_seed(seed)

        result = self.pipeline(
            prompt=self.PROMPT,
            negative_prompt=self.NEGATIVE_PROMPT,
            image=texture_image,
            strength=strength,
            guidance_scale=guidance_scale,
            num_inference_steps=num_inference_steps,
            generator=generator,
        )
        output = result.images[0]
        return self._to_heightmap(output)

    @staticmethod
    def _to_heightmap(img: Image.Image) -> Image.Image:
        gray = img.convert("L")
        arr = np.array(gray, dtype=np.float32)
        lo, hi = arr.min(), arr.max()
        if hi > lo:
            arr = (arr - lo) / (hi - lo) * 255.0
        return Image.fromarray(arr.astype(np.uint8), mode="L")

    def generate_interpolated(
        self,
        texture_a: Union[str, Image.Image],
        texture_b: Union[str, Image.Image],
        alpha: float = 0.5,
        **kwargs,
    ) -> Image.Image:
        """Generate a heightmap interpolated between two reference textures.

        Blends the two input images in pixel space before passing to the pipeline.
        For latent-space interpolation, use inference/interpolate_textures.py.
        """
        if isinstance(texture_a, str):
            texture_a = Image.open(texture_a).convert("RGB")
        if isinstance(texture_b, str):
            texture_b = Image.open(texture_b).convert("RGB")

        size = kwargs.get("output_size", 512)
        a = np.array(texture_a.resize((size, size))).astype(np.float32)
        b = np.array(texture_b.resize((size, size))).astype(np.float32)
        blended = Image.fromarray(((1 - alpha) * a + alpha * b).clip(0, 255).astype(np.uint8))
        return self.generate(blended, **kwargs)

    def unload(self):
        """Free GPU memory."""
        if self.pipeline is not None:
            del self.pipeline
            self.pipeline = None
            self._loaded = False
            if torch.cuda.is_available():
                torch.cuda.empty_cache()


def build_lora_unet(unet, rank: int = 4, alpha: int = 16):
    """Attach LoRA adapters to all cross-attention layers in the UNet.

    Called during fine-tuning (train_heightmap.py).
    Requires: pip install peft>=0.9.0
    """
    try:
        from peft import LoraConfig, get_peft_model
    except ImportError as e:
        raise ImportError("Install peft: pip install peft>=0.9.0") from e

    target_modules = [
        "to_q", "to_k", "to_v", "to_out.0",
        "proj_in", "proj_out",
    ]
    config = LoraConfig(
        r=rank,
        lora_alpha=alpha,
        target_modules=target_modules,
        lora_dropout=0.05,
        bias="none",
    )
    return get_peft_model(unet, config)
